# Documentation on the kinds of information to go in this build file:
# https://docs.acquia.com/cloud-platform/develop/pipelines/yaml/
#
# See real examples on customizing pipelines:
# https://github.com/acquia/pipelines-examples

version: 1.2.0
services:
  - mysql
  - php:
      version: 7.4

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt

events:
  build:
    steps:
      - setup-env:
          type: script
          script:
            - composer validate --no-check-all --ansi
            - composer install --ansi
            - source ${BLT_DIR}/scripts/pipelines/setup_env
            # Uncomment these lines if front-end theming requires it.
            # - nvm install v6.9.1
            # - npm install --global yarn
      - validate:
          type: script
          script:
            - source ${BLT_DIR}/scripts/pipelines/validate
      # Uncomment these lines to test database updates using live content.
      # - test-updates:
      #     type: script
      #     script:
      #       - blt drupal:sync:default:site
      - setup-app:
          type: script
          script:
            - source ${BLT_DIR}/scripts/pipelines/setup_app
      # Uncomment these lines when automated testing is in place and ready.
      # - tests:
      #     type: script
      #     script:
      #       - source ${BLT_DIR}/scripts/pipelines/tests
      - build-artifact:
          type: script
          script:
            - source ${BLT_DIR}/scripts/pipelines/build_artifact
  # Uncomment these lines if you want something to happen when a build fails
  # or when a branch is deployed.
  # fail-on-build:
  #   steps:
  #     - runonfailure:
  #         type: script
  #         script:
  #           - "echo 'This is simple echo from fail-on-build event'"
  # post-deploy:
  #   steps:
  #     - runonpostdeploy:
  #         type: script
  #         script:
  #           - "echo 'This is simple echo from post-deploy event'"
