/**
 * @file Scripting for site-wide headers.
 */

(function ($, Drupal) {
  "use strict";

  /***
   * Position main header-navigation fly-outs.
   *
   * The header main-navigation has flyout generated by Bootstrap and the
   * Radix theme. These are positioned (once opened) absolutely, below the
   * parent menu item. We'd instead like to show them directly below the
   * horizontal stripe of the header.
   *
   * Since that would take unsetting "position: relative" on many parent
   * containers, just calculate the container height and set a new "top"
   * position.
   */
  Drupal.behaviors.westyMenuPosition2 = {
    attach: function (context) {

      const container = document.querySelector(".page__main_header nav.navbar");
      const navLinks = container.querySelectorAll(".nav-item");

      [].forEach.call(navLinks, function(link) {

        link.addEventListener('show.bs.dropdown', function () {
          console.log('there2')
          // let navLinkFlyout = container.querySelector(".dropdown-menu.show");
          // navLinkFlyout.style.top =
          //   container.offsetHeight - navParentLink.offsetHeight + "px";
        })

      });

    },

  };

})(jQuery, Drupal);
