<?php

use Drupal\Core\Entity;
use Drupal\Core\Form\FormStateInterface;/**
 * Implements hook_form_FORM_ID_alter().
 */
function wcor_inline_media_edit_form_editor_media_dialog_alter(array &$form, FormStateInterface $form_state)
{

  if (isset($form_state->getUserInput()['editor_object'])) {
    $editor_object = $form_state->getUserInput()['editor_object'];
    $media_embed_element = $editor_object['attributes'];
  } else {
    // Retrieve the user input from form state.
    $media_embed_element = $form_state->get('media_embed_element');
  }
  $uuid = $media_embed_element['data-entity-uuid'];
  $file = \Drupal::service('entity.repository')->loadEntityByUuid('media', $uuid);
  $bundle= $file->bundle();
  // $editor_object['label']

  // Modify document embeds
  if ($bundle == 'document'){
    $form['data-title'] = [
      '#title' => t('Override title:'),
      '#type' => 'textfield',
      '#step' => '1',
      '#default_value' => empty($media_embed_element['data-title']) ? '' : $media_embed_element['data-title'],
      '#parents' => ['attributes', 'data-title'],
    ];
    $form['data-description'] = [
      '#title' => t('Display description?'),
      '#type' => 'checkbox',
      '#step' => '2',
      '#default_value' => empty($media_embed_element['data-description']) ? false : true,
      '#parents' => ['attributes', 'data-description'],
    ];
  }

}
